---
# 1) 패키지 설치
# CentOS 환경 확인 후 httpd 패키지를 설치한다.

- name: 1-0) CentOS 환경 확인
  ansible.builtin.fail:
    msg: "이 role은 CentOS 환경 기준으로 작성됨"
  when: ansible_distribution != "CentOS"

- name: 1-1) WEB 패키지 설치 - httpd
  ansible.builtin.dnf:
    name: "{{ web_packages }}"
    state: present
